//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.10

pub use super::game::Entity as Game;
// pub use super::player::Entity as Player;
pub use super::turn::Entity as Turn;
pub use super::user::Entity as User;
